/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MyModel(props) {
  const { nodes, materials } = useGLTF('')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body11.geometry} material={nodes.Body11.material} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
